static_pages:
    resource: "@StaticPagesBundle/Controller/"
    type:     annotation
    prefix:   /

core_bundle:
    resource: "@CoreBundle/Controller/"
    type: annotation
    prefix: /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"