static_pages:
    resource: "@StaticPagesBundle/Controller/"
    type:     annotation
    prefix:   /

entity:
    resource: "@EntityBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"